name: ${PROJECT}
description: ${DESCRIPTION}
runtime: nodejs

template:
  description: A TypeScript Pulumi program to set up Pulumi Deployments Review Stacks
  config:
    repositoryRef:
      description: The GitHub repo to add Review Stacks. (Pulumi GH App access required)
      default: desteves/pulumi-reviewstacks-demo
    branchRef:
      description: The GitHub repo branch to add Review Stacks.
      default: refs/heads/main
    repoDirRef:
      description: The GitHub repo folder where the Pulumi.<stack>.yaml is located. Use '.' for root.
      default: infra
    projectRef:
      description: The Pulumi project to reference
      default: workshop
    stackRef:
      description: The Pulumi stack to reference
      default: dev
